# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 23cb3b67eea5259ad7214ade81d8df17d7fe033ee16d31e46e6cc94e7b4b3a452779cbf7aff2ef57aceb183987b40a10306ca80eefaa54e71f55c5148f2b9dca

test:
  secret_key_base: cd13963aa30190897ccf8cafbfebd158859e8f2501a142f4df58eb3af538678901642f257753224110131e337ed39e0bdfa4b37304ead8745d4caada306e605d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
